AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Name:
    Type: String
    Description: Provide the stage of the project

  Value:
    Type: String
    Description: Provide the stage of the project



Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref Name
      Type: String
      Value: !Ref Value
      Description: SSM Parameter of type String new.
